// src/editor/ObjectivesSheet.tsx
import type { Dispatch } from "react";

import type { Issue } from "../api/types";
import { AutoTextarea } from "./AutoTextarea";
import { replaceItem } from "./edit";
import { IssueList } from "./IssueList";
import { issuesAt } from "./issues";
import type { EditorAction } from "./state";

interface Props {
	objectives: string[];
	issues: Issue[];
	dispatch: Dispatch<EditorAction>;
}

export function ObjectivesSheet({ objectives, issues, dispatch }: Props) {
	return (
		<section className="sheet">
			<h2>Программное содержание</h2>
			<IssueList issues={issuesAt(issues, "objectives")} />
			{objectives.map((objective, i) => {
				const own = issuesAt(issues, `objectives[${i}]`);
				return (
					<div key={i}>
						<div className="objective">
							<span className="number">{i + 1}</span>
							<AutoTextarea
								aria-label={`Цель ${i + 1}`}
								rows={3}
								className={own.length > 0 ? "invalid" : ""}
								value={objective}
								onChange={(e) =>
									dispatch({
										type: "fieldsChanged",
										fields: {
											objectives: replaceItem(objectives, i, e.target.value),
										},
									})
								}
							/>
							<button
								type="button"
								onClick={() => dispatch({ type: "objectiveRemoved", index: i })}
							>
								Удалить
							</button>
						</div>
						<IssueList issues={own} />
					</div>
				);
			})}
			<button
				type="button"
				onClick={() => dispatch({ type: "objectiveAdded" })}
			>
				+ Добавить цель
			</button>
		</section>
	);
}

// src/editor/ObjectivesSheet.svelte
<script lang="ts">
	import AutoTextarea from "./AutoTextarea.svelte";
	import type { Draft } from "./draft.svelte";
	import IssueList from "./IssueList.svelte";
	import { issuesAt } from "./issues";

	let { draft }: { draft: Draft } = $props();
</script>

<section class="sheet">
	<h2>Программное содержание</h2>
	<IssueList issues={issuesAt(draft.issues, "objectives")} />
	{#each draft.fields.objectives as _, i (i)}
		{@const own = issuesAt(draft.issues, `objectives[${i}]`)}
		<div>
			<div class="objective">
				<span class="number">{i + 1}</span>
				<AutoTextarea
					aria-label="Цель {i + 1}"
					rows={3}
					class={own.length > 0 ? "invalid" : ""}
					bind:value={draft.fields.objectives[i]}
				/>
				<button
					type="button"
					onclick={() => draft.removeObjective(i)}
				>
					Удалить
				</button>
			</div>
			<IssueList issues={own} />
		</div>
	{/each}
	<button
		type="button"
		onclick={() => draft.addObjective()}
	>
		+ Добавить цель
	</button>
</section>
